name: Deploy Web App by omkar

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Simulate deployment
      run: |
        echo "Starting deployment..."
        ls webapp
        cat webapp/index.html
        echo "Deployment complete!"

